task: node_classification #link_prediction

dataset_name: Wisconsin
split: public
nsplit: 0

missing_link: 0.0
missing_feature: 0.0

nnbrs: [-1, -1]
train_bs: 90941
val_bs: 90941
test_bs: 90941

lr: 0.01
weight_decay: 0.005
num_epochs: 50
loss_fn: ce
optimizer: Adam

early_stopping: False
es_patience: 5
es_min_delta: 0.0001
min_loss_change: 0.001

metrics:
  - ACC
  - f1_wtd
  - f1_macro
  # - report
  # - f1_micro
